os: linux
dist: xenial
language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
install:
  - npm install
script:
    - npm run build
jobs:
  include:
    - stage: deploy
      node_js: 14
      install: npm install
      script: npm run build
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_token : "$NPM_API_TOKEN"
        cleanup: false
        on:
          tags: true