os: linux
dist: xenial
language: node_js
node_js: 10
env:
  - CHAN1=$CHAN1
  - CHAN2=$CHAN2
  - SERVER1=$SERVER1
  - SERVER2=$SERVER2
  - GIN=$GIN
before_install:
  - npm install -g snyk
  - npm install -g nyc
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
    - npm run build
    - nyc --reporter=lcov --include=src/* npm run test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT