os: linux
dist: xenial
language: node_js
node_js: 10
before_install:
  - npm install -g snyk
install:
  - npm install
script:
    - npm run build
    - npm run test
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_token: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+