os: linux
dist: xenial
language: node_js
node_js: 10
install:
  - npm install --quiet
script:
    - npm run build
    - npm run test
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_token: $NPM_AUTH_TOKEN
  cleanup: false
  on:
    branch: master
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+