os: linux
dist: xenial
language: node_js
node_js: 
  - 10
  - 11
  - 12
  - 13
  - 14
install:
  - npm install
script:
    - npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key : "$NPM_API_TOKEN"
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVS_COMMIT_MESSAGE =~ (v[0-9]\.[0-9]\.[0-9])