language: node_js
node_js: "10"
install:
  - npm install --quiet
script:
    - npm run build
    - npm run test
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_AUTH_TOKEN"
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+"
    node: "10"