name: build
on:
  push:
    branches:
     - main
  pull_request:
    branches:
      - main
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Running build without doc
      run: |
        npm install
        node ./node_modules/ts-node/dist/bin.js ./build/copyfiles.ts
        node ./node_modules/typescript/bin/tsc
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  publish:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: MontyD/package-json-updated-action@1.0.1
      id: version-updated
      with:
        path: package.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      if: steps.version-updated.outputs.has-updated
    - uses: actions/setup-node@v1
      if: steps.version-updated.outputs.has-updated
      with:
        node-version: 14
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
      if: steps.version-updated.outputs.has-updated
    - run: npm publish
      if: steps.version-updated.outputs.has-updated
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
